// Code generated by protoc-gen-go. DO NOT EDIT.
// source: v2ray.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Uuid                 string   `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Level                uint32   `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
	AlterId              uint32   `protobuf:"varint,4,opt,name=alterId,proto3" json:"alterId,omitempty"`
	Enable               uint32   `protobuf:"varint,5,opt,name=enable,proto3" json:"enable,omitempty"`
	TransferEnable       int64    `protobuf:"varint,6,opt,name=transfer_enable,json=transferEnable,proto3" json:"transfer_enable,omitempty"`
	Uplink               int64    `protobuf:"varint,7,opt,name=uplink,proto3" json:"uplink,omitempty"`
	Downlink             int64    `protobuf:"varint,8,opt,name=downlink,proto3" json:"downlink,omitempty"`
	UpIncr               int64    `protobuf:"varint,9,opt,name=upIncr,proto3" json:"upIncr,omitempty"`
	DownIncr             int64    `protobuf:"varint,10,opt,name=downIncr,proto3" json:"downIncr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_v2ray_7934547de0bb3411, []int{0}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *User) GetLevel() uint32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *User) GetAlterId() uint32 {
	if m != nil {
		return m.AlterId
	}
	return 0
}

func (m *User) GetEnable() uint32 {
	if m != nil {
		return m.Enable
	}
	return 0
}

func (m *User) GetTransferEnable() int64 {
	if m != nil {
		return m.TransferEnable
	}
	return 0
}

func (m *User) GetUplink() int64 {
	if m != nil {
		return m.Uplink
	}
	return 0
}

func (m *User) GetDownlink() int64 {
	if m != nil {
		return m.Downlink
	}
	return 0
}

func (m *User) GetUpIncr() int64 {
	if m != nil {
		return m.UpIncr
	}
	return 0
}

func (m *User) GetDownIncr() int64 {
	if m != nil {
		return m.DownIncr
	}
	return 0
}

type UserRepo struct {
	Usermap              map[string]*User `protobuf:"bytes,1,rep,name=usermap,proto3" json:"usermap,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *UserRepo) Reset()         { *m = UserRepo{} }
func (m *UserRepo) String() string { return proto.CompactTextString(m) }
func (*UserRepo) ProtoMessage()    {}
func (*UserRepo) Descriptor() ([]byte, []int) {
	return fileDescriptor_v2ray_7934547de0bb3411, []int{1}
}
func (m *UserRepo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRepo.Unmarshal(m, b)
}
func (m *UserRepo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRepo.Marshal(b, m, deterministic)
}
func (dst *UserRepo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRepo.Merge(dst, src)
}
func (m *UserRepo) XXX_Size() int {
	return xxx_messageInfo_UserRepo.Size(m)
}
func (m *UserRepo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRepo.DiscardUnknown(m)
}

var xxx_messageInfo_UserRepo proto.InternalMessageInfo

func (m *UserRepo) GetUsermap() map[string]*User {
	if m != nil {
		return m.Usermap
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "pb.user")
	proto.RegisterType((*UserRepo)(nil), "pb.user_repo")
	proto.RegisterMapType((map[string]*User)(nil), "pb.user_repo.UsermapEntry")
}

func init() { proto.RegisterFile("v2ray.proto", fileDescriptor_v2ray_7934547de0bb3411) }

var fileDescriptor_v2ray_7934547de0bb3411 = []byte{
	// 282 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x91, 0x3d, 0x6f, 0x83, 0x30,
	0x10, 0x86, 0x65, 0x48, 0xf8, 0x38, 0xfa, 0x25, 0xab, 0x8a, 0x2c, 0x86, 0x0a, 0x65, 0x29, 0x13,
	0x03, 0xed, 0x50, 0x75, 0x6e, 0x86, 0xac, 0x48, 0x9d, 0x23, 0x53, 0xae, 0x52, 0x14, 0xc7, 0x58,
	0x0e, 0x50, 0xf1, 0x0b, 0x3a, 0xf6, 0x2f, 0x57, 0x36, 0x98, 0x76, 0xc2, 0xcf, 0xfb, 0xdc, 0x8b,
	0xe0, 0x0c, 0xc9, 0x50, 0x6a, 0x3e, 0x16, 0x4a, 0xb7, 0x5d, 0x4b, 0x3d, 0x55, 0x6f, 0x7f, 0x3c,
	0x58, 0xf5, 0x17, 0xd4, 0x34, 0x85, 0xc8, 0x3c, 0x25, 0x3f, 0x23, 0x23, 0x19, 0xc9, 0xe3, 0x6a,
	0x61, 0x4a, 0x61, 0xd5, 0xf7, 0xc7, 0x86, 0x79, 0x36, 0xb7, 0x67, 0x7a, 0x0f, 0x6b, 0x81, 0x03,
	0x0a, 0xe6, 0x67, 0x24, 0xbf, 0xae, 0x26, 0xa0, 0x0c, 0x42, 0x2e, 0x3a, 0xd4, 0xfb, 0x86, 0xad,
	0x6c, 0xee, 0x90, 0x6e, 0x20, 0x40, 0xc9, 0x6b, 0x81, 0x6c, 0x6d, 0xc5, 0x4c, 0xf4, 0x11, 0x6e,
	0x3b, 0xcd, 0xe5, 0xe5, 0x13, 0xf5, 0x61, 0x1e, 0x08, 0x32, 0x92, 0xfb, 0xd5, 0x8d, 0x8b, 0x77,
	0xd3, 0xe0, 0x06, 0x82, 0x5e, 0x89, 0xa3, 0x3c, 0xb1, 0xd0, 0xfa, 0x99, 0xcc, 0x87, 0x37, 0xed,
	0x97, 0xb4, 0x26, 0xb2, 0x66, 0xe1, 0xa9, 0xb3, 0x97, 0x1f, 0x9a, 0xc5, 0xae, 0x63, 0xc8, 0x75,
	0xac, 0x81, 0xbf, 0x8e, 0xe1, 0xed, 0x37, 0x81, 0xd8, 0xfc, 0xf9, 0x41, 0xa3, 0x6a, 0xe9, 0x33,
	0x84, 0x06, 0xce, 0x5c, 0x31, 0x92, 0xf9, 0x79, 0x52, 0xa6, 0x85, 0xaa, 0x8b, 0xc5, 0x17, 0xef,
	0x93, 0xdc, 0xc9, 0x4e, 0x8f, 0x95, 0x1b, 0x4d, 0xdf, 0xe0, 0xea, 0xbf, 0xa0, 0x77, 0xe0, 0x9f,
	0x70, 0x9c, 0xf7, 0x6a, 0x8e, 0xf4, 0x01, 0xd6, 0x03, 0x17, 0x3d, 0xda, 0x9d, 0x26, 0x65, 0xe4,
	0xde, 0x5a, 0x4d, 0xf1, 0xab, 0xf7, 0x42, 0xea, 0xc0, 0x5e, 0xd3, 0xd3, 0x6f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x2e, 0x75, 0x5c, 0x45, 0xb5, 0x01, 0x00, 0x00,
}
